export enum GENDERS {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
}

export enum JOB_LEVEL {
  INTERN = 'INTERN',
  JUNIOR = 'JUNIOR',
  MIDDLE = 'MIDDLE',
  SENIOR = 'SENIOR',
  MANAGER = 'MANAGER',
}

// PENDING-REVIEWING-APPROVED-REJECTED
export enum RESUME_STATUS {
  PENDING = 'PENDING',
  REVIEWING = 'REVIEWING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum API_METHOD {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE',
  PATCH = 'PATCH',
  HEAD = 'HEAD',
}
