export enum ROLES {
  USER = 'USER',
  ADMIN = 'ADMIN',
}

export enum GENDERS {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
}

export enum JOB_LEVEL {
  INTERN = 'INTERN',
  JUNIOR = 'JUNIOR',
  MIDDLE = 'MIDDLE',
  SENIOR = 'SENIOR',
  MANAGER = 'MANAGER',
}

// PENDING-REVIEWING-APPROVED-REJECTED
export enum RESUME_STATUS {
  PENDING = 'PENDING',
  REVIEWING = 'REVIEWING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
