export const ENV = {
  PORT: 'PORT',
  MONGODB_URI: 'MONGODB_URI',
  ACCESS_TOKEN_SECRET: 'ACCESS_TOKEN_SECRET',
  ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
  REFRESH_TOKEN_SECRET: 'REFRESH_TOKEN_SECRET',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
} as const;
